/**
 * Surface publique de @vtex/core.
 *
 * Le Core expose son routeur générique et son type. Les produits
 * composent ce routeur avec leurs propres procédures métier ; aucune
 * dépendance à un domaine produit n'est importée ici.
 */
export { coreRouter } from "./api/router"
export type { CoreRouter } from "./api/router"
export { mergeRouters, protectedProcedure, publicProcedure, router } from "./api/trpc"
export { db } from "./db/client"
export type { Db } from "./db/client"
export { bankAccounts, cardVault, documentFiles, documents, logs, managerAssignments, notificationReads, notifications, sessions, supportSessions, supportTickets, users, WALLET_TYPES } from "./db/schema"
export type { SupportSession } from "./db/schema"
export { deleteAssignment, insertAssignment, isWalletAssigned, listAssignments, listAssignmentsOfMany, listManagersOfWallet, walletKey } from "./modules/managers/assignments"
export type { AssignmentRow } from "./modules/managers/assignments"
export { createSystemNotification, insertSuggestions } from "./modules/notifications/service"
export { publishRealtime } from "./modules/realtime/events"
export { resolveDownload } from "./modules/documents/service"
export { MAX_MEDIA_BYTES, adminUploadKey, assertAcceptedMedia, assertMediaSignature, assertPrivateObject, detectMediaType, getPrivateObject, putPrivateObject, safeFileName, sha256Hex, userUploadKey } from "./modules/media/objectStorage"
export type { BankAccountRow, CardVaultRow, WalletType } from "./db/schema"
export { mysqlSslOption } from "./db/sslOption"
export { ForbiddenError, NotFoundError, STAFF_ROLES, ValidationError, isAdminRole, isStaffRole, requireRole, requireSelfOrRole } from "./auth/permissions"
export type { Actor, Role } from "./auth/permissions"
export { PERMISSIONS, ROLE_PERMISSIONS, assertCanAssignRole, can, requirePermission } from "./auth/rbac"
export type { Permission } from "./auth/rbac"
export { assertPasswordPolicy, generateTemporaryPassword, hashPassword, verifyPassword } from "./auth/password"
export { revokeAllSessions } from "./auth/session"
export { currentRequestContext, runWithRequestContext } from "./api/requestContext"
export { clientIp, toRequestContext } from "./api/context"
export { logAction, listLogsForHolder } from "./modules/journal/service"
export { TEMP_PASSWORD_DEFAULT_TTL_HOURS, adminResetPassword, insertUserRow, listUsers, reactivateUser, safeUserColumns, suspendUser } from "./modules/users/service"
export type { CreateUserInput } from "./modules/users/service"
export { RateLimitError, checkRateLimit } from "./api/rateLimit"
export { getSimGateway, getStripeGateway, stripeAdminStatus, stripePublicConfig, topupDailyRemaining, topupLimits, topupLimitsByCurrency, TOPUP_DAILY_MAX_EUR_CENTS, TOPUP_MAX_EUR_CENTS } from "./stripe/gateway"
export { CURRENCY_SYMBOLS, canConvert, convertMinor, eurEquivalentMinor, EUR_XPF_RATE, floorConvertMinor, formatMinor, minorDivisor } from "./stripe/fx"
export type { MoneyCurrency } from "./stripe/fx"
export { formatIban, generatedIban, generatedVirtualIban, maskIbanValue, normalizeAndValidateBic, normalizeAndValidateIban } from "./iban"
export type { GatewayEvent, IntentSnapshot, IntentStatus, StripeGateway, StripeMode, StripePublicConfig } from "./stripe/gateway"
export { VaultIntegrityError, VaultUnavailableError, activeVaultKeyId } from "./modules/vault/crypto"
export { EMPTY_CARD_VAULT_STATUS, cardVaultStatus, cardVaultStatuses, clearCardSecrets, cvvStorageAllowed, detectNetwork, luhnValid, normalizeCvv, normalizePan, normalizePin, revealCardSecrets, storeCardSecrets } from "./modules/vault/cardVault"
export type { CardRef, CardSecretField, CardVaultStatus, RevealedCardSecrets } from "./modules/vault/cardVault"
export { attachBankAccount, bankAccountView, findActiveMain, getBankAccount, ibanFingerprint, insertBankAccount, openIban, revealBankAccountIban, sealIban, setBankAccountStatus, syncMainBankAccount, updateBankAccount } from "./modules/banking/bankAccounts"
export type { BankAccountKind, BankAccountPatch, BankAccountView, MainBankRef, NewBankAccount } from "./modules/banking/bankAccounts"
export { buildEpcPayload, renderEpcQrSvg } from "./modules/banking/epcQr"
export type { EpcQrInput } from "./modules/banking/epcQr"
export { assertOperatorAccess, endAccessSession, getMyActiveAccessSession, listAccessSessionsForHolder, startAccessSession } from "./modules/support/accessSessions"
export type { AccessSessionMode } from "./modules/support/accessSessions"
