CREATE TABLE IF NOT EXISTS `wallet_topups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(100) NOT NULL,
  `wallet_account_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `amount_cents` BIGINT NOT NULL,
  `currency` CHAR(3) NOT NULL,
  `status` ENUM('pending','requires_action','processing','succeeded','failed','canceled') NOT NULL DEFAULT 'pending',
  `stripe_mode` ENUM('sim','test','live') NOT NULL,
  `stripe_payment_intent_id` VARCHAR(80),
  `card_brand` VARCHAR(24),
  `card_last4` CHAR(4),
  `failure_code` VARCHAR(64),
  `failure_message` VARCHAR(250),
  `transaction_id` BIGINT,
  `credited_at` DATETIME,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `wallet_topups_reference_unique` (`reference`),
  UNIQUE KEY `wallet_topups_idempotency_key_unique` (`idempotency_key`),
  UNIQUE KEY `wallet_topups_intent_unique` (`stripe_payment_intent_id`),
  KEY `wallet_topups_user_created_idx` (`user_id`, `created_at`),
  KEY `wallet_topups_status_idx` (`status`),
  CONSTRAINT `wallet_topups_account_fk` FOREIGN KEY (`wallet_account_id`) REFERENCES `wallet_accounts` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `wallet_topups_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `wallet_topups_transaction_fk` FOREIGN KEY (`transaction_id`) REFERENCES `transactions` (`id`) ON DELETE SET NULL
);--> statement-breakpoint
ALTER TABLE `transactions` MODIFY COLUMN `type` ENUM('transfer_internal','transfer_external','split_debit','split_credit','savings_deposit','savings_withdrawal','card_payment','fee','adjustment','topup') NOT NULL;
