import { NotFoundError, checkRateLimit, db, protectedProcedure, publicProcedure, router } from "@vtex/core"
import { CURRENCY_CODES } from "@vtex/money"
import { z } from "zod"
import {
  adminAdjustBusinessBalance,
  adminAssignBusinessBankDetails,
  adminRevokeBusinessBankDetails,
  adminBusinessKpis,
  adminCreateBusiness,
  adminDecidePayout,
  adminListAdminTransactions,
  adminListPendingPayouts,
  approvePayout,
  businessKpis,
  businessRoleMatrix,
  convertEstimateToInvoice,
  createApplication,
  createBusiness,
  createCard,
  createCustomer,
  createEstimate,
  createInvoice,
  createOrder,
  createPayout,
  createPayoutBatch,
  createPaymentLink,
  createProduct,
  createSubscription,
  createWebhook,
  decideApproval,
  getAdminBusinessDetail,
  getBusinessSettings,
  getBusinessWallet,
  getMyBusinesses,
  inviteMember,
  listAdminBusinesses,
  listApplications,
  listApprovals,
  listBusinessBankAccounts,
  listCards,
  listChargebacks,
  listCustomers,
  listDisputes,
  listEstimates,
  listInvoices,
  listMembers,
  listOrders,
  listPaymentLinks,
  listPayoutBatches,
  listPayouts,
  listProducts,
  listRiskFlags,
  listSubscriptions,
  listTransactions,
  listWebhookDeliveries,
  listWebhooks,
  provisionBankDetails,
  recordInvoicePayment,
  rejectPayout,
  removeMember,
  resolveRiskFlag,
  revokeApplication,
  setCardFrozen,
  toggleWebhook,
  updateBusiness,
  updateBusinessSettings,
  updateCardControls,
  updateChargebackStatus,
  updateCustomer,
  updateDisputeStatus,
  updateEstimateStatus,
  updateInvoiceStatus,
  updateAdminBusinessStatus,
  updateMemberRole,
  updateMemberStatus,
  updateOrderStatus,
  updatePaymentLinkStatus,
  updateProduct,
  updateSubscriptionStatus,
} from "./service"
import { platformEnvironment } from "./apiV1"
import { API_SCOPES, API_SCOPE_IDS, createApiKey, listApiKeys, revokeApiKey, rotateApiKey } from "./apiKeys"
import { confirmPublicPayment, getPublicPaymentLink, recentPaymentsOfLink, simAuthenticatePublicPayment, simPayPublicPayment, startPublicPayment } from "./paymentLinkPay"
import { businessStripeStatus, businessTopupConfig, cancelBusinessTopup, confirmBusinessTopup, createBusinessTopup, listAdminBusinessTopups, listBusinessTopups, reconcileBusinessTopup, refundBusinessTopup, simAuthenticateBusinessTopup, simPayBusinessTopup } from "./topups"

const businessId = z.object({ businessId: z.number().int().positive() })
const cents = z.number().int().safe().positive()
const currency = z.enum(CURRENCY_CODES)
const lineItems = z.array(z.object({ description: z.string().min(1).max(250), quantity: z.number().int().positive(), unitPriceCents: cents })).min(1)

const businessWriteProcedure = protectedProcedure.use(async ({ ctx, next }) => {
  await checkRateLimit(db, `business:write:${ctx.actor.id}:${ctx.ip}`, 40, 60_000)
  return next()
})
const businessMoneyProcedure = protectedProcedure.use(async ({ ctx, next }) => {
  await checkRateLimit(db, `business:money:${ctx.actor.id}:${ctx.ip}`, 10, 60_000)
  return next()
})

export const businessRouter = router({
  businesses: router({
    mine: protectedProcedure.query(({ ctx }) => getMyBusinesses(ctx.actor)),
    create: businessWriteProcedure.input(z.object({ legalName: z.string().min(2).max(160), brandName: z.string().min(2).max(100), industry: z.string().max(100).optional(), siren: z.string().max(20).optional(), vatId: z.string().max(32).optional(), email: z.string().email().optional(), phone: z.string().max(32).optional(), address: z.string().max(250).optional(), currency: currency.optional() })).mutation(({ ctx, input }) => createBusiness(ctx.actor, input)),
    update: businessWriteProcedure.input(businessId.extend({ legalName: z.string().min(2).max(160).optional(), brandName: z.string().min(2).max(100).optional(), industry: z.string().max(100).optional(), siren: z.string().max(20).optional(), vatId: z.string().max(32).optional(), email: z.string().email().optional(), phone: z.string().max(32).optional(), address: z.string().max(250).optional(), logoUrl: z.string().max(300).optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => updateBusiness(ctx.actor, id, rest)),
    kpis: protectedProcedure.input(businessId).query(({ ctx, input }) => businessKpis(ctx.actor, input.businessId)),
    settings: protectedProcedure.input(businessId).query(({ ctx, input }) => getBusinessSettings(ctx.actor, input.businessId)),
    updateSettings: businessWriteProcedure.input(businessId.extend({ checkoutBrandColor: z.string().max(7).optional(), invoicePrefix: z.string().max(12).optional(), defaultCurrency: currency.optional(), notifyEmail: z.boolean().optional(), notifySms: z.boolean().optional(), notifyPush: z.boolean().optional(), require2fa: z.boolean().optional(), ipAllowlist: z.array(z.string()).optional(), sessionTimeoutMinutes: z.number().int().min(5).max(1440).optional(), integrations: z.record(z.boolean()).optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => updateBusinessSettings(ctx.actor, id, rest)),
  }),
  team: router({
    roleMatrix: protectedProcedure.query(() => businessRoleMatrix),
    listMembers: protectedProcedure.input(businessId).query(({ ctx, input }) => listMembers(ctx.actor, input.businessId)),
    invite: businessWriteProcedure.input(businessId.extend({ userId: z.number().int().positive(), role: z.enum(["owner", "admin", "finance", "support", "viewer"]) })).mutation(({ ctx, input }) => inviteMember(ctx.actor, input.businessId, { userId: input.userId, role: input.role })),
    updateRole: businessWriteProcedure.input(businessId.extend({ memberId: z.number().int().positive(), role: z.enum(["owner", "admin", "finance", "support", "viewer"]) })).mutation(({ ctx, input }) => updateMemberRole(ctx.actor, input.businessId, input.memberId, input.role)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ memberId: z.number().int().positive(), status: z.enum(["active", "suspended"]) })).mutation(({ ctx, input }) => updateMemberStatus(ctx.actor, input.businessId, input.memberId, input.status)),
    remove: businessWriteProcedure.input(businessId.extend({ memberId: z.number().int().positive() })).mutation(({ ctx, input }) => removeMember(ctx.actor, input.businessId, input.memberId)),
    listApprovals: protectedProcedure.input(businessId.extend({ status: z.enum(["pending", "approved", "rejected"]).optional() })).query(({ ctx, input }) => listApprovals(ctx.actor, input.businessId, input.status)),
    decideApproval: businessWriteProcedure.input(businessId.extend({ approvalId: z.number().int().positive(), decision: z.enum(["approved", "rejected"]), reason: z.string().max(250).optional() })).mutation(({ ctx, input }) => decideApproval(ctx.actor, input.businessId, input.approvalId, input.decision, input.reason)),
  }),
  wallet: router({
    accounts: protectedProcedure.input(businessId).query(({ ctx, input }) => getBusinessWallet(ctx.actor, input.businessId)),
    provisionBankDetails: businessWriteProcedure.input(businessId.extend({ accountId: z.number().int().positive() })).mutation(({ ctx, input }) => provisionBankDetails(ctx.actor, input.businessId, input.accountId)),
    bankAccounts: protectedProcedure.input(businessId).query(({ ctx, input }) => listBusinessBankAccounts(ctx.actor, input.businessId)),
    listCards: protectedProcedure.input(businessId).query(({ ctx, input }) => listCards(ctx.actor, input.businessId)),
    createCard: businessWriteProcedure.input(businessId.extend({ businessWalletAccountId: z.number().int().positive(), cardholderName: z.string().min(2).max(140), assignedToUserId: z.number().int().positive().optional(), network: z.enum(["visa", "mastercard", "cb"]), theme: z.enum(["navy", "teal", "brick"]), label: z.string().max(80).optional(), expiresAt: z.coerce.date() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createCard(ctx.actor, id, rest)),
    setCardFrozen: businessWriteProcedure.input(businessId.extend({ cardId: z.number().int().positive(), frozen: z.boolean() })).mutation(({ ctx, input }) => setCardFrozen(ctx.actor, input.businessId, input.cardId, input.frozen)),
    updateCardControls: businessWriteProcedure.input(businessId.extend({ cardId: z.number().int().positive(), onlinePaymentsEnabled: z.boolean().optional(), contactlessEnabled: z.boolean().optional(), cashWithdrawalEnabled: z.boolean().optional(), dailyLimitCents: cents.optional(), monthlyLimitCents: cents.optional(), perTransactionLimitCents: cents.optional() })).mutation(({ ctx, input: { businessId: id, cardId, ...rest } }) => updateCardControls(ctx.actor, id, cardId, rest)),
    listTransactions: protectedProcedure.input(businessId.extend({ limit: z.number().int().positive().max(200).optional() })).query(({ ctx, input }) => listTransactions(ctx.actor, input.businessId, input.limit)),
  }),
  payouts: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listPayouts(ctx.actor, input.businessId)),
    listBatches: protectedProcedure.input(businessId).query(({ ctx, input }) => listPayoutBatches(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ businessWalletAccountId: z.number().int().positive(), beneficiaryName: z.string().min(2).max(160), iban: z.string().min(15).max(34), bic: z.string().max(11).optional(), amountCents: cents, currency: currency.optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createPayout(ctx.actor, id, rest)),
    createBatch: businessWriteProcedure.input(businessId.extend({ label: z.string().min(2).max(120), items: z.array(z.object({ beneficiaryName: z.string().min(2).max(160), iban: z.string().min(15).max(34), bic: z.string().max(11).optional(), amountCents: cents, currency: currency.optional() })).min(1) })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createPayoutBatch(ctx.actor, id, rest)),
    approve: businessWriteProcedure.input(businessId.extend({ payoutId: z.number().int().positive() })).mutation(({ ctx, input }) => approvePayout(ctx.actor, input.businessId, input.payoutId)),
    reject: businessWriteProcedure.input(businessId.extend({ payoutId: z.number().int().positive(), reason: z.string().max(250).optional() })).mutation(({ ctx, input }) => rejectPayout(ctx.actor, input.businessId, input.payoutId, input.reason)),
  }),
  customers: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listCustomers(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ name: z.string().min(2).max(160), email: z.string().email().optional(), phone: z.string().max(32).optional(), company: z.string().max(160).optional(), address: z.string().max(250).optional(), notes: z.string().max(2000).optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createCustomer(ctx.actor, id, rest)),
    update: businessWriteProcedure.input(businessId.extend({ customerId: z.number().int().positive(), name: z.string().max(160).optional(), email: z.string().email().optional(), phone: z.string().max(32).optional(), company: z.string().max(160).optional(), address: z.string().max(250).optional(), notes: z.string().max(2000).optional(), status: z.enum(["active", "blocked"]).optional() })).mutation(({ ctx, input: { businessId: id, customerId, ...rest } }) => updateCustomer(ctx.actor, id, customerId, rest)),
  }),
  paymentLinks: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listPaymentLinks(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ name: z.string().min(2).max(160), amountCents: cents, currency: currency.optional(), mode: z.enum(["unique", "recurring"]), targetAccountId: z.number().int().positive().optional(), description: z.string().max(250).optional(), expiresAt: z.coerce.date().optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createPaymentLink(ctx.actor, id, rest)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ linkId: z.number().int().positive(), status: z.enum(["active", "expired", "draft", "disabled"]) })).mutation(({ ctx, input }) => updatePaymentLinkStatus(ctx.actor, input.businessId, input.linkId, input.status)),
    payments: protectedProcedure.input(businessId.extend({ linkId: z.number().int().positive() })).query(async ({ ctx, input }) => { await listPaymentLinks(ctx.actor, input.businessId).then((links) => { if (!links.some((link) => link.id === input.linkId)) throw new NotFoundError("Lien de paiement introuvable.") }); return recentPaymentsOfLink(input.linkId) }),
  }),
  /** Paiement public par lien : aucune session, aucun compte. Chaque procédure est limitée en débit par IP et ne renvoie jamais d'identifiant interne. */
  publicPayments: router({
    get: publicProcedure.input(z.object({ slug: z.string().min(4).max(24) })).query(({ ctx, input }) => getPublicPaymentLink(input.slug, ctx.ip)),
    start: publicProcedure.input(z.object({ slug: z.string().min(4).max(24), payerName: z.string().min(2).max(160), payerEmail: z.string().max(160), idempotencyKey: z.string().min(16).max(100) })).mutation(({ ctx, input }) => startPublicPayment(input, ctx.ip)),
    confirm: publicProcedure.input(z.object({ reference: z.string().min(8).max(64) })).mutation(({ ctx, input }) => confirmPublicPayment(input.reference, ctx.ip)),
    simPay: publicProcedure.input(z.object({ reference: z.string().min(8).max(64), cardNumber: z.string().min(12).max(23) })).mutation(({ ctx, input }) => simPayPublicPayment(input, ctx.ip)),
    simAuthenticate: publicProcedure.input(z.object({ reference: z.string().min(8).max(64) })).mutation(({ ctx, input }) => simAuthenticatePublicPayment(input.reference, ctx.ip)),
  }),
  invoices: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listInvoices(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ customerId: z.number().int().positive(), dueAt: z.coerce.date(), description: z.string().max(250).optional(), items: lineItems })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createInvoice(ctx.actor, id, rest)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ invoiceId: z.number().int().positive(), status: z.enum(["draft", "sent", "viewed", "cancelled"]) })).mutation(({ ctx, input }) => updateInvoiceStatus(ctx.actor, input.businessId, input.invoiceId, input.status)),
    recordPayment: businessWriteProcedure.input(businessId.extend({ invoiceId: z.number().int().positive(), amountCents: cents, method: z.enum(["card", "transfer", "payment_link", "manual"]).optional() })).mutation(({ ctx, input }) => recordInvoicePayment(ctx.actor, input.businessId, input.invoiceId, input.amountCents, input.method)),
  }),
  estimates: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listEstimates(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ customerId: z.number().int().positive(), validUntil: z.coerce.date().optional(), items: lineItems })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createEstimate(ctx.actor, id, rest)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ estimateId: z.number().int().positive(), status: z.enum(["sent", "accepted", "declined", "expired"]) })).mutation(({ ctx, input }) => updateEstimateStatus(ctx.actor, input.businessId, input.estimateId, input.status)),
    convertToInvoice: businessWriteProcedure.input(businessId.extend({ estimateId: z.number().int().positive(), dueAt: z.coerce.date() })).mutation(({ ctx, input }) => convertEstimateToInvoice(ctx.actor, input.businessId, input.estimateId, input.dueAt)),
  }),
  subscriptions: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listSubscriptions(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ customerId: z.number().int().positive(), planName: z.string().min(2).max(120), amountCents: cents, currency: currency.optional(), interval: z.enum(["monthly", "yearly"]) })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createSubscription(ctx.actor, id, rest)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ subscriptionId: z.number().int().positive(), status: z.enum(["active", "paused", "cancelled"]) })).mutation(({ ctx, input }) => updateSubscriptionStatus(ctx.actor, input.businessId, input.subscriptionId, input.status)),
  }),
  products: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listProducts(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ name: z.string().min(2).max(160), sku: z.string().max(64).optional(), priceCents: cents, currency: currency.optional(), stock: z.number().int().min(0).optional(), category: z.string().max(100).optional(), description: z.string().max(500).optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createProduct(ctx.actor, id, rest)),
    update: businessWriteProcedure.input(businessId.extend({ productId: z.number().int().positive(), name: z.string().max(160).optional(), priceCents: cents.optional(), stock: z.number().int().min(0).optional(), category: z.string().max(100).optional(), description: z.string().max(500).optional(), status: z.enum(["active", "archived"]).optional() })).mutation(({ ctx, input: { businessId: id, productId, ...rest } }) => updateProduct(ctx.actor, id, productId, rest)),
  }),
  orders: router({
    list: protectedProcedure.input(businessId).query(({ ctx, input }) => listOrders(ctx.actor, input.businessId)),
    create: businessWriteProcedure.input(businessId.extend({ customerId: z.number().int().positive().optional(), channel: z.enum(["pos", "online", "manual"]), items: z.array(z.object({ productId: z.number().int().positive().optional(), description: z.string().min(1).max(250), quantity: z.number().int().positive(), unitPriceCents: cents })).min(1) })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createOrder(ctx.actor, id, rest)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ orderId: z.number().int().positive(), status: z.enum(["paid", "fulfilled", "refunded", "cancelled"]) })).mutation(({ ctx, input }) => updateOrderStatus(ctx.actor, input.businessId, input.orderId, input.status)),
  }),
  resolution: router({
    listDisputes: protectedProcedure.input(businessId).query(({ ctx, input }) => listDisputes(ctx.actor, input.businessId)),
    updateDisputeStatus: businessWriteProcedure.input(businessId.extend({ disputeId: z.number().int().positive(), status: z.enum(["under_review", "won", "lost"]) })).mutation(({ ctx, input }) => updateDisputeStatus(ctx.actor, input.businessId, input.disputeId, input.status)),
    listChargebacks: protectedProcedure.input(businessId).query(({ ctx, input }) => listChargebacks(ctx.actor, input.businessId)),
    updateChargebackStatus: businessWriteProcedure.input(businessId.extend({ chargebackId: z.number().int().positive(), status: z.enum(["accepted", "represented", "won", "lost"]) })).mutation(({ ctx, input }) => updateChargebackStatus(ctx.actor, input.businessId, input.chargebackId, input.status)),
    listRiskFlags: protectedProcedure.input(businessId).query(({ ctx, input }) => listRiskFlags(ctx.actor, input.businessId)),
    resolveRiskFlag: businessWriteProcedure.input(businessId.extend({ flagId: z.number().int().positive(), status: z.enum(["dismissed", "confirmed"]) })).mutation(({ ctx, input }) => resolveRiskFlag(ctx.actor, input.businessId, input.flagId, input.status)),
  }),
  developers: router({
    apiScopes: protectedProcedure.query(() => API_SCOPE_IDS.map((id) => ({ id, ...API_SCOPES[id] }))),
    /** « live » quand la plateforme encaisse en réel, « sandbox » sinon : une clé d'un autre environnement est refusée par /api/v1. */
    environment: protectedProcedure.query(() => ({ environment: platformEnvironment() })),
    listApiKeys: protectedProcedure.input(businessId).query(({ ctx, input }) => listApiKeys(ctx.actor, input.businessId)),
    createApiKey: businessWriteProcedure.input(businessId.extend({ label: z.string().min(2).max(100), mode: z.enum(["live", "sandbox"]), scopes: z.array(z.enum(API_SCOPE_IDS)).min(1), expiresAt: z.coerce.date().optional() })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createApiKey(ctx.actor, id, rest)),
    rotateApiKey: businessWriteProcedure.input(businessId.extend({ keyId: z.number().int().positive(), graceHours: z.number().int().min(0).max(72) })).mutation(({ ctx, input }) => rotateApiKey(ctx.actor, input.businessId, input.keyId, input.graceHours)),
    revokeApiKey: businessWriteProcedure.input(businessId.extend({ keyId: z.number().int().positive(), reason: z.string().max(250).optional() })).mutation(({ ctx, input }) => revokeApiKey(ctx.actor, input.businessId, input.keyId, input.reason)),
    listApplications: protectedProcedure.input(businessId).query(({ ctx, input }) => listApplications(ctx.actor, input.businessId)),
    createApplication: businessWriteProcedure.input(businessId.extend({ name: z.string().min(2).max(120), redirectUris: z.array(z.string().url()).min(1) })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createApplication(ctx.actor, id, rest)),
    revokeApplication: businessWriteProcedure.input(businessId.extend({ applicationId: z.number().int().positive() })).mutation(({ ctx, input }) => revokeApplication(ctx.actor, input.businessId, input.applicationId)),
    listWebhooks: protectedProcedure.input(businessId).query(({ ctx, input }) => listWebhooks(ctx.actor, input.businessId)),
    createWebhook: businessWriteProcedure.input(businessId.extend({ url: z.string().url(), events: z.array(z.string()).min(1) })).mutation(({ ctx, input: { businessId: id, ...rest } }) => createWebhook(ctx.actor, id, rest)),
    toggleWebhook: businessWriteProcedure.input(businessId.extend({ webhookId: z.number().int().positive(), status: z.enum(["active", "disabled"]) })).mutation(({ ctx, input }) => toggleWebhook(ctx.actor, input.businessId, input.webhookId, input.status)),
    listWebhookDeliveries: protectedProcedure.input(businessId.extend({ webhookId: z.number().int().positive() })).query(({ ctx, input }) => listWebhookDeliveries(ctx.actor, input.businessId, input.webhookId)),
  }),
  businessTopups: router({
    config: protectedProcedure.input(businessId).query(({ ctx, input }) => businessTopupConfig(ctx.actor, input.businessId)),
    create: businessMoneyProcedure.input(businessId.extend({ businessWalletAccountId: z.number().int().positive(), amountCents: cents.positive(), currency: currency.optional(), billingName: z.string().max(160).optional(), idempotencyKey: z.string().min(16).max(100) })).mutation(({ ctx, input }) => createBusinessTopup(ctx.actor, input)),
    confirm: businessWriteProcedure.input(z.object({ reference: z.string().min(8).max(64) })).mutation(({ ctx, input }) => confirmBusinessTopup(ctx.actor, input.reference)),
    list: protectedProcedure.input(businessId.extend({ limit: z.number().int().min(1).max(50).optional() })).query(({ ctx, input }) => listBusinessTopups(ctx.actor, input.businessId, input.limit)),
    simPay: businessMoneyProcedure.input(z.object({ reference: z.string().min(8).max(64), cardNumber: z.string().min(12).max(23) })).mutation(({ ctx, input }) => simPayBusinessTopup(ctx.actor, input)),
    simAuthenticate: businessWriteProcedure.input(z.object({ reference: z.string().min(8).max(64) })).mutation(({ ctx, input }) => simAuthenticateBusinessTopup(ctx.actor, input.reference)),
  }),
  businessAdmin: router({
    stripeStatus: protectedProcedure.query(({ ctx }) => businessStripeStatus(ctx.actor)),
    topups: protectedProcedure.input(z.object({ status: z.enum(["pending", "requires_action", "processing", "succeeded", "failed", "canceled", "refunded"]).optional(), limit: z.number().int().min(1).max(500).optional() }).optional()).query(({ ctx, input }) => listAdminBusinessTopups(ctx.actor, input)),
    reconcileTopup: businessWriteProcedure.input(z.object({ reference: z.string().min(8).max(64) })).mutation(({ ctx, input }) => reconcileBusinessTopup(ctx.actor, input.reference)),
    cancelTopup: businessWriteProcedure.input(z.object({ reference: z.string().min(8).max(64) })).mutation(({ ctx, input }) => cancelBusinessTopup(ctx.actor, input.reference)),
    refundTopup: businessMoneyProcedure.input(z.object({ reference: z.string().min(8).max(64), reason: z.string().min(8).max(250) })).mutation(({ ctx, input }) => refundBusinessTopup(ctx.actor, input)),
    kpis: protectedProcedure.query(({ ctx }) => adminBusinessKpis(ctx.actor)),
    listBusinesses: protectedProcedure.query(({ ctx }) => listAdminBusinesses(ctx.actor)),
    createBusiness: businessWriteProcedure.input(z.object({ ownerUserId: z.number().int().positive(), legalName: z.string().min(2).max(160), brandName: z.string().min(2).max(100), industry: z.string().max(100).optional(), siren: z.string().max(20).optional(), vatId: z.string().max(32).optional(), email: z.string().email().optional(), phone: z.string().max(32).optional(), address: z.string().max(250).optional(), currency: currency.optional() })).mutation(({ ctx, input }) => adminCreateBusiness(ctx.actor, input)),
    detail: protectedProcedure.input(businessId).query(({ ctx, input }) => getAdminBusinessDetail(ctx.actor, input.businessId)),
    updateStatus: businessWriteProcedure.input(businessId.extend({ status: z.enum(["active", "suspended", "closed"]) })).mutation(({ ctx, input }) => updateAdminBusinessStatus(ctx.actor, input.businessId, input.status)),
    adjustBalance: businessWriteProcedure.input(businessId.extend({ accountId: z.number().int().positive(), deltaCents: z.number().int(), reason: z.string().min(8).max(250) })).mutation(({ ctx, input }) => adminAdjustBusinessBalance(ctx.actor, input.businessId, input.accountId, input.deltaCents, input.reason)),
    updateBankDetails: businessWriteProcedure.input(businessId.extend({ accountId: z.number().int().positive(), iban: z.string().min(15).max(34), bic: z.string().min(8).max(11), reason: z.string().min(8).max(250) })).mutation(({ ctx, input }) => adminAssignBusinessBankDetails(ctx.actor, input)),
    revokeBankDetails: businessWriteProcedure.input(businessId.extend({ accountId: z.number().int().positive(), reason: z.string().min(8).max(250) })).mutation(({ ctx, input }) => adminRevokeBusinessBankDetails(ctx.actor, input)),
    listTransactions: protectedProcedure.input(z.object({ limit: z.number().int().positive().max(500).optional() }).optional()).query(({ ctx, input }) => adminListAdminTransactions(ctx.actor, input?.limit)),
    listPendingPayouts: protectedProcedure.query(({ ctx }) => adminListPendingPayouts(ctx.actor)),
    decidePayout: businessWriteProcedure.input(businessId.extend({ payoutId: z.number().int().positive(), decision: z.enum(["approved", "rejected"]), reason: z.string().max(250).optional() })).mutation(({ ctx, input }) => adminDecidePayout(ctx.actor, input.businessId, input.payoutId, input.decision, input.reason)),
  }),
})
